services:
  - type: worker
    name: rostelekom-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
    envVars:
      - key: TOKEN
        value: 7239749525:AAHSHRQgDoJ41ts-DFzWY4NWZWW1wX-nSGQ
      - key: ADMIN_ID
        value: 911720830
